name: Build everything
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Release
        uses: brpaz/action-semantic-release@v1
        with:
          dry_run: "false"
          branch: master
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}